import numpy as np
import h5py
import scanpy as sc
'''''''''
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Mouse_Brain_Sagittal_Posterior_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename="V1_Mouse_Brain_Sagittal_Posterior_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Adult_Mouse_Brain_Coronal_Section_2_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename="V1_Adult_Mouse_Brain_Coronal_Section_2_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Adult_Mouse_Brain_Coronal_Section_1_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename="V1_Adult_Mouse_Brain_Coronal_Section_1_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Human_Brain_Section_2_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "V1_Human_Brain_Section_2_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Human_Brain_Section_1_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "V1_Human_Brain_Section_1_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="5k_pbmc_protein_v3_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "5k_pbmc_protein_v3_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Adult_Mouse_Brain_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "V1_Adult_Mouse_Brain_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Human_Lymph_Node_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "V1_Human_Lymph_Node_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="Targeted_Visium_Human_OvarianCancer_Pan_Cancer_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "Targeted_Visium_Human_OvarianCancer_Pan_Cancer_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Human_Heart_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "V1_Human_Heart_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="Visium_FFPE_Human_Breast_Cancer_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "Visium_FFPE_Human_Breast_Cancer_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Mouse_Kidney_filtered_feature_bc_matrix.h5",load_images=False)
anndata1.var_names_make_unique()
anndata1.write(filename= "V1_Mouse_Kidney_filtered_feature_bc_matrix.h5ad", compression=None, compression_opts=None, force_dense=None, as_dense=())
'''''
#anndata1=sc.read_visium("/home1/zhaolianhe/SPDB/10Xgenomics", genome=None, count_file="V1_Mouse_Kidney_filtered_feature_bc_matrix.h5",load_images=False)
#anndata1.var_names_make_unique()
#print(anndata1)
#print(anndata1.X)
